name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Create environment config
      run: |
        echo "window.ENV_CONFIG = {" > js/env-config.js
        echo "  FIREBASE_API_KEY: '${{ secrets.FIREBASE_API_KEY }}'," >> js/env-config.js
        echo "  FIREBASE_AUTH_DOMAIN: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'," >> js/env-config.js
        echo "  FIREBASE_PROJECT_ID: '${{ secrets.FIREBASE_PROJECT_ID }}'," >> js/env-config.js
        echo "  FIREBASE_STORAGE_BUCKET: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'," >> js/env-config.js
        echo "  FIREBASE_MESSAGING_SENDER_ID: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'," >> js/env-config.js
        echo "  FIREBASE_APP_ID: '${{ secrets.FIREBASE_APP_ID }}'" >> js/env-config.js
        echo "};" >> js/env-config.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.PAT_20250810 }}
        publish_dir: ./
        exclude_assets: '.github,README.md,FIREBASE_SETUP.md,GITHUB_SETUP.md'
